Translated #17. Ready for proofreading.
vojtapolasek/Fegora pull request #29
Opened 2021-11-01 09:34 UTC by lruzicka

This is a translation of the above mentioned section, ready for proofreading.

2021-11-09 17:01 UTC, vojtapolasek requested changes
Thank you, see comments please.

2021-11-09 17:01 UTC, vojtapolasek commented on docs/handout_en.md
> +the **Space** key.
```suggestion
the **Spacebar** key.
```

2021-11-09 17:01 UTC, vojtapolasek commented on docs/handout_en.md
> +You can add more panels, or add icons to the current panels. Use
```suggestion
You can add more panels, or add icons to already existing panels. Use 
```

2021-11-09 17:01 UTC, vojtapolasek commented on docs/handout_en.md
> +the **Shift+F10** combination to open the corresponding dialogue.
```suggestion
the **Shift+F10** combination to open the corresponding menu.
```

2021-11-18 11:52 UTC, lruzicka commented on docs/handout_en.md
> +**Shift+Tab** to thumb trough the particular items. On the panel, you
Changed.

2021-11-18 12:10 UTC, lruzicka commented
I have made the required changes.

2021-11-28 10:09 UTC, vojtapolasek approved these changes

2021-11-28 10:10 UTC, vojtapolasek commented
Hello, thank you very much for the changes. Merging.

2021-11-28 10:10 UTC, merged