Translate #18. Ready for proofreading.
vojtapolasek/Fegora pull request #30
Opened 2021-11-01 10:35 UTC by lruzicka

The translation proposal for the Web Browsing chapter.

2021-11-09 16:58 UTC, vojtapolasek requested changes
Thank you so much, see comments please.

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +navigate between links and form items. Orca offers the browsing modes
```suggestion
navigate between links and form items. Orca offers two modes
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +The *browsing mode* is recommended whenever you need to browse through
```suggestion
The *browse mode* is recommended whenever you need to browse through
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +that you can use to move among the control items. For instance, the **H**
```suggestion
that you can use to move among the page elements. For instance, the **H**
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +The *targetting mode* corresponds with the *form mode* in NVDA. You will
```suggestion
The *focus mode* corresponds with the *form mode* in NVDA. You will
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +into entry fields, toggle switches, and so on. This would not work in the
```suggestion
into form fields, toggle switches, and so on. This would not work in the
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +the form and should immediately switch to the targetting mode. This is only
```suggestion
a form and should immediately switch to the targetting mode. This is only
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +indicated in the voice, however not by any sound. To toggle the modes manually,
```suggestion
indicated by the speech but not by any sound. To toggle the modes manually,
```

2021-11-09 16:58 UTC, vojtapolasek commented on docs/handout_en.md
> +of this combo, the targetting mode will lock and stay active even upon leaving
```suggestion
of this combo, the focus mode will lock and stay active even upon leaving
```

2021-11-18 12:08 UTC, lruzicka commented
I have made the required changes.

2021-11-28 10:12 UTC, vojtapolasek approved these changes

2021-11-28 10:12 UTC, vojtapolasek commented
Thank you for the changes. Merging.

2021-11-28 10:12 UTC, merged