Translate #15, ready for proofreading.
vojtapolasek/Fegora pull request #31
Opened 2021-11-01 10:59 UTC by lruzicka

Please, check the button, tab and settings descriptions as I do not have any Fegora installed and could not see the real life English translations. Thanks.

2021-11-09 16:48 UTC, vojtapolasek requested changes
see my comments, accept suggestions if you think they make sense. thank you.

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +## Quick introduction to the Orca reader
```suggestion
## Quick introduction to the Orca screenreader
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +dialogue can be activated using **Orca+Space**. The cursor can be found on
```suggestion
dialogue can be activated using **Orca+Space**. The focus will be placed on
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +a row of tabs which can be switched using the **right and left arrows**.
```suggestion
a row of tabs which can be browsed using the **right and left arrows**. 
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +The **Tab** key iterates over the control items (**Shift+Tab** in the reversed
```suggestion
The **Tab** key iterates over the controls (**Shift+Tab** in the reversed 
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +order). The buttons, check-buttons and radio-buttons can be activated using the
```suggestion
order). The buttons, checkboxes and radio-buttons can be activated using the 
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +**Space** key. Any list item is selected using the **up and down arrows**.
```suggestion
**Spacebar** key. Any list item is selected using the **up and down arrows**. 
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +changes, mind to activate the **OK** button.
```suggestion
changes, remember to activate the **OK** button.
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +change the layout to **Desktop**, the Orca key will be moved to the **Insert**
```suggestion
change the layout to **Desktop**, the Orca key will be set to the **Insert**
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +might want to change the voice synthesis. You can do so on the **Voice** tab.
```suggestion
might want to change the voice synthesis. You can do so on the **Speech** tab.
```

2021-11-09 16:48 UTC, vojtapolasek commented on docs/handout_en.md
> +Change only the **Voice input** and **Person** values and leave the **Speech
```suggestion
Change only the **Speech Synthesizer** and **Person** values and leave the **Speech
```

2021-11-18 12:09 UTC, lruzicka commented
I have made the required changes.

2021-11-28 10:15 UTC, vojtapolasek approved these changes

2021-11-28 10:16 UTC, vojtapolasek commented
Thank you for all changes. Merging.

2021-11-28 10:16 UTC, merged