Translated #14. Ready for proofreading.
vojtapolasek/Fegora pull request #32
Opened 2021-11-18 12:44 UTC by lruzicka

I have translated another part of the text, please check that out.

2021-11-28 10:23 UTC, vojtapolasek requested changes
Thank you for the changes. Please see comments. Also, it seems that the part about web browsing has been already translated. Please remove it from this PR.

2021-11-28 10:23 UTC, vojtapolasek commented on docs/handout_en.md
> +workplace. You need to do it after the system starts, otherwise it will
```suggestion
desktop. You need to do it after the system starts, otherwise it will 
```

2021-11-28 10:23 UTC, vojtapolasek commented on docs/handout_en.md
> +Now you are on the workplace. Using the arrows, you can browse through several
```suggestion
Now you are on the desktop. Using the arrows, you can browse through several 
```

2021-11-28 10:23 UTC, vojtapolasek commented on docs/handout_en.md
> +On the workplace, there will be a very interesting file called `keyboard_shortcuts.txt`
```suggestion
On the desktop there will be a very interesting file called `keyboard_shortcuts.txt`
```

2021-11-28 10:23 UTC, vojtapolasek commented on docs/handout_en.md
> +probably notice that text editting works as in Windows. You can close the text editor
```suggestion
probably notice that text editing works as in Windows. You can close the text editor
```

2021-11-28 10:23 UTC, vojtapolasek commented on docs/handout_en.md
> +On the workspace, the `handout.html` file is located, too, and you are probably
```suggestion
The `handout.html` file is located on the desktop as well, and you are probably
```

2021-11-29 07:39 UTC, lruzicka commented
Hi, I did not quite understand what you meant by removing the translated **Web browsing** but I have freshly rebased this branch and I believe that it is fully compatible with the main branch now.

2021-12-25 15:05 UTC, vojtapolasek commented
Thank you for this translation, merging.

2021-12-25 15:05 UTC, vojtapolasek approved these changes

2021-12-25 15:05 UTC, merged